server:
    port: 9000

management:
    address: 127.0.0.1
    port: 9100

logging:
    level:
        com.slgerkamp.daily.life: DEBUG

spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:/tmp/h2-dailyLife
        username: sa
        password:
    jpa:
        hibernate.ddl-auto: validate
    thymeleaf.cache: false

    mail:
      host: localhost
      port: 10025

dailylife.file:
    tmpstorage: /tmp/dailylife/tmpstorage
    storage: /tmp/dailylife/storage
